### ISSUE TITLE
Usage docs

### ISSUE THREAD

**Issue by KronosTheLate** [jverzani/QuizQuestions.jl#1]
I do not intent to use this package, I was just curious. But it seems to me that if I wanted to ute it, I could not - there is nothing about usage in the readme, and no documentation page. 

Maybie that could be added?

**Comment by KronosTheLate** [comment]
Docs don't work :/
![msedge_grpuivleiq](https://user-images.githubusercontent.com/61620837/152488345-5f7256b3-1348-47f4-81b5-1023f5a2b93d.gif)

**Comment by jverzani** [comment]
Yup, but — hopefully — once this gets on the registry and I tag a new release it will. (Being lazy, i let juliahub host them.)
