### ISSUE TITLE
Get Documenter deployment of documentation working

### ISSUE THREAD

**Issue by jverzani** [jverzani/QuizQuestions.jl#16]
Striking out trying to follow the documenter docs and trying to just let juliahub build and host. Ugghhh.

**Comment by sylvaticus** [comment]
Sorry, but why are you using juliahub in the first instance ? You don't need it, just use the github pages.. you were very close, you had the documentation correctly built on  the `gh-pages` branch....

**Comment by jverzani** [comment]
Yes, why? Because I've had no-muss success with other packages using JuliaHub (though not here) and for the life of me couldn't get gh-pages properly setup, despite following the instructions faithfully (though likely I skipped some step along the way). Maybe I'll give it another go, but yesterday I got impatient.

**Comment by sylvaticus** [comment]
Have a look at my [Tutorial](https://syl1.gitbook.io/julia-language-a-concise-tutorial/language-core/11-developing-julia-packages) and [Dummy implementation](https://github.com/sylvaticus/MyAwesomePackage.jl)

Adding the `deploydoc` call  in make.jl you were able to get the documentation built, as I saw it.

The last step was to go to the settings of your package and set the source to the `gh-pages` branch (see the [GitHub own documentation](https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site) on pages)
End at the next push the documentation will (well.. should..) be available to https://jverzani.github.io//QuizQuestions

**Comment by jverzani** [comment]
Thanks again! I think this can get closed in a few minutes....

**Comment by sylvaticus** [comment]
Super :-)

You'll get the "stable" version automatically the first time you publish a release on github...
