### ISSUE TITLE
Simplyfy text visualised to say "correct" on stringq and "numericq"

### ISSUE THREAD

**Issue by sylvaticus** [jverzani/QuizQuestions.jl#17]
Hello, a minor thing...  I think for `numericq` and `stringq` a "Correct !" message would be more than enough than showing the actual check done to determine correctness:

![image](https://user-images.githubusercontent.com/2077159/162462627-12a6754d-325e-4bda-b9c4-3819daa9ca05.png)

**Comment by jverzani** [comment]
Didn't I fix that with the last release? (it is a bug in an attempt to make the "Correct!" configurable in case that was desirable.)

**Comment by sylvaticus** [comment]
That is with the last released version:

` QuizQuestions v0.3.4`

**Comment by jverzani** [comment]
Are you sure. For some reason Pluto is only picking up v0.3.3, but the file hasn't changed in v0.3.4
<img width="617" alt="Screen Shot 2022-04-08 at 11 51 01 AM" src="https://user-images.githubusercontent.com/421708/162478430-8e951e7c-499f-4f28-b434-1f3ac7036ce5.png">

**Comment by sylvaticus** [comment]
"👍  Correct", sorry, I had 0.3 still loaded in memory..
