### ISSUE TITLE
Does not work on Pluto :(

### ISSUE THREAD

**Issue by fonsp** [jverzani/QuizQuestions.jl#35]
Hallo!

I tried to use QuizQuestions.jl on Pluto but it does not seem to work

<img width="1440" alt="image" src="https://github.com/jverzani/QuizQuestions.jl/assets/6933510/91b6e275-d217-4d87-a9e0-727ad47c5691">

**Comment by fonsp** [comment]
For globals, you could use `window.quizquestions_scorecard` instead of just `quizquestions_scorecard`. 

Also check out:
- https://javascript.info/optional-chaining
- https://javascript.info/variables
- https://javascript.info/var

**Comment by fonsp** [comment]
An alternative approach to managing the global state of the scorecard:

Make the score an HTML attribute of the question element. Whenever a score changes, fire a `new CustomEvent("quizquestions score changed")` on `window`. 
Then the scorecard can just have an event listener on `window`. The listener function uses `document.querySelectorAll` to find all questions currently displayed on the page, and `map` and `reduce` to get their total scores.

This way, you don't need the `ID`, and you don't need to worry about questions being removed/changed and leaving global state.

Hope this is useful! If any of this is unclear, I really recommend the crowd-sourced resource javascript.info for learning more about browser API :)

**Comment by jverzani** [comment]
Thanks for the comment and especially the suggested alternative! Will try to address ASAP.
