### ISSUE TITLE
Add support for multiple choices question & feedback

### ISSUE THREAD

**Issue by sylvaticus** [jverzani/QuizQuestions.jl#4]
Hello, I am playing with your very nice package, and wonder if it would be easy to add support for multiple choices questions (where the correct answers could be more than one) and for an overall "feedback" when one has correctly answered or asked explicitly for it.
The "problem" I can see is that you use Mustache, and I guess this is why the "solution" is based on hover and not on buttons, as there is no JS involved (I think)
So with multiple choices the focus rule can't be used, there should be explicitly an "Answer" and a "See correct answers" button.. what do you think ?

**Comment by jverzani** [comment]
The Mustache is just for templating, so shouldn't limit the use of HTML or JavaScript. What is best for this (basically so it can fit into Pluto) is to not rely on any external JavaScript libraries.

So let me see what you have here:

- [ x] Multiple choice questions (see #6). There is a handler each time one of the checkboxes is toggled that computes all the selected boxes and compares by index, to those that are indicated as answers. Currently there is a determination of `correct` or not, but there is room for more nuance here. 

- [ ] overall feedback. The `grading_partial` variable could be used here. That is called once "correct" is computed. There is also the `hint` that can be passed and could be mimicked if you wanted more than that. In #6 I made the words "Correct" and "Incorrect" customizable, but certainly more sophisticated things could be done.

**Comment by sylvaticus** [comment]
Addressed by [release v0.2.0](https://github.com/jverzani/QuizQuestions.jl/releases/tag/v0.2.0)
