### ISSUE TITLE
Add support to matching questions

### ISSUE THREAD

**Issue by sylvaticus** [jverzani/QuizQuestions.jl#9]
Hello, do you think it would be possible to add support for matching questions ? 

![image](https://user-images.githubusercontent.com/2077159/161787640-86d63008-62f3-4f74-9354-51948da55161.png)

**Comment by jverzani** [comment]
Seems doable, but I might not get to it for a week or two.

**Comment by jverzani** [comment]
Well, should have said a few hours #10. Let me know what tweaks you want (I see you had "choose..." as default boilerplate just now, and I left it blank) and if it does what you were expecting. If it meets your muster, I'll merge it in.

**Comment by sylvaticus** [comment]
Thank you, it works for me.
I was going to suggest you to add an example to the documenter-generated documentation, but I see you already have done it in index.md ;-)

Thank you again

**Comment by jverzani** [comment]
Okay, I want to add one more interface (a dictionary of question => answer) and will then merge in.

**Comment by jverzani** [comment]
closed by #10

**Comment by jverzani** [comment]
I merged this and thought I had the docs set up so they would show through juliahub, but my setup skills are lagging. Need to learn a bit before they documentation shows examples.
